project-config:
  env: production
  # 是否开启登录验证码
  login-captcha-enabled: true

# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 生产环境禁用 Swagger 文档
springdoc:
  api-docs:
    enabled: false
